# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Minz Won"
resume_title:                   "Research Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "minzwon@bytedance.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "0"
resume_contact_address:         "Los Angeles"

resume_header_contact_info:     "minz.won@upf.edu<br>Currently in Seoul &#127472;&#127479;"
display_header_contact_info:    "true"

resume_header_intro: "<p>I research machine learning to enhance listeners' music experience. <br>My research interest covers audio representation learning, natural language processing, and multimodality. <br><br>A fan of Barça and Packers. <br>I collect vinyl records. <br><br>Feel free to contact me &#129305;</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_publications:    true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_twitter_url:           "http://twitter.com/minzwon"
  resume_instagram_url:         "https://instagram.com/minzwon"
  resume_github_url:            "https://github.com/minzwon"
  resume_google_scholar_url:    "https://scholar.google.com/citations?user=x5rArQMAAAAJ&hl=en&oi=ao"
  resume_linkedin_url:          "https://www.linkedin.com/in/minzwon"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
